apiVersion: v1
kind: Service
metadata:
  name: configurable-np
  labels: 
    co.courselabs.k8sfun: productionizing
spec:
  selector:
    app: configurable
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30040
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: configurable-lb
  labels: 
    co.courselabs.k8sfun: productionizing
spec:
  selector:
    app: configurable
  ports:
    - name: http
      port: 8040
      targetPort: 80
  type: LoadBalancer