apiVersion: v1
kind: Service
metadata:
  name: legacy-web
  labels:
    kubernetes.courselabs.co: api-versions
    app: legacy-web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: legacy-web
