apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo
  labels:
    kubernetes.courselabs.co: api-versions
    app: api-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-demo
  template:
    metadata:
      labels:
        app: api-demo
    spec:
      containers:
        - name: whoami
          image: containous/whoami:latest
          ports:
            - containerPort: 80
