apiVersion: apps/v1
kind: Deployment
metadata:
  name: vweb-bg-blue
  labels:
    app: vweb-bg
    strategy: blue-green
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vweb-bg
      version: blue
  template:
    metadata:
      labels:
        app: vweb-bg
        version: blue
    spec:
      containers:
      - name: web
        image: kiamol/ch09-vweb:v1
        ports:
        - containerPort: 80
          name: http
