apiVersion: apps/v1
kind: Deployment
metadata:
  name: vweb-bg-green
  labels:
    app: vweb-bg
    strategy: blue-green
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vweb-bg
      version: green
  template:
    metadata:
      labels:
        app: vweb-bg
        version: green
    spec:
      containers:
      - name: web
        image: kiamol/ch09-vweb:v2
        ports:
        - containerPort: 80
          name: http
