apiVersion: v1
kind: Service
metadata:
  name: vweb-bg-svc
  labels:
    app: vweb-bg
    strategy: blue-green
spec:
  type: NodePort
  selector:
    app: vweb-bg
    version: blue  # Initially points to blue
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30019
    protocol: TCP
    name: http
