apiVersion: apps/v1
kind: Deployment
metadata:
  name: vweb-canary-canary
  labels:
    app: vweb-canary
    track: canary
spec:
  replicas: 1  # Start with just 1 pod (20% of total)
  selector:
    matchLabels:
      app: vweb-canary
      track: canary
  template:
    metadata:
      labels:
        app: vweb-canary
        track: canary
    spec:
      containers:
      - name: web
        image: kiamol/ch09-vweb:v2
        ports:
        - containerPort: 80
          name: http
