apiVersion: v1
kind: Service
metadata:
  name: vweb-canary-svc
  labels:
    app: vweb-canary
spec:
  type: NodePort
  selector:
    app: vweb-canary  # Selects both stable and canary pods
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30020
    protocol: TCP
    name: http
