apiVersion: apps/v1
kind: Deployment
metadata:
  name: vweb-canary-stable
  labels:
    app: vweb-canary
    track: stable
spec:
  replicas: 4
  selector:
    matchLabels:
      app: vweb-canary
      track: stable
  template:
    metadata:
      labels:
        app: vweb-canary
        track: stable
    spec:
      containers:
      - name: web
        image: kiamol/ch09-vweb:v1
        ports:
        - containerPort: 80
          name: http
