# service
servicePort: 8020
serviceType: NodePort
serviceNodePort: 30820

# deployment
replicaCount: 3
serverImage: docker.io/courselabs/whoami-lab:21.09-4
serverMode: q

# registry
privateImageRegistry: false
registrySecretName: none